version: '3.3'
volumes:
    dbdata:
      driver: local
    static:
      driver: local
    media:
      driver: local

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf://etc/nginx/conf.d/default.conf
      - media:/app/media
      - static:/app/static
    
  django:
    build:
      context: ./django
    restart: always
    volumes:
      - ./django/src:/app/src
      - media:/app/media
      - static:/app/static

  db:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: postgres
    volumes:
    - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2.5
    restart: always